name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Go Code
        uses: docker://golangci/golangci-lint:latest
        with:
          args: golangci-lint run ./... --enable golint,unparam,misspell

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.11, 1.12, 1.13, 1.14]
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute local tests
        run: go test -v -coverprofile=cover.out -cover ./...

      - name: Generate coverage report
        run: go tool cover -html=cover.out -o coverage.html

      - name: Upload code coverage report
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report-${{ matrix.go }}
          path: coverage.html

  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.11, 1.12, 1.13, 1.14]
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go install
        run: go install ./...
